job:
  image: 'hmctspublic.azurecr.io/sscs/case-migration:latest'
  aadIdentityName: sscs
  ingressHost: sscs-case-migration-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  keyVaults:
    sscs:
      resourceGroup: sscs
      secrets:
        - name: idam-oauth-user
          alias: IDAM_OAUTH2_CLIENT_ID
        - name: idam-sscs-oauth2-client-secret
          alias: IDAM_OAUTH2_CLIENT_SECRET
        - name: idam-sscs-systemupdate-user
          alias: IDAM_SSCS_SYSTEMUPDATE_USER
        - name: idam-sscs-systemupdate-password
          alias: IDAM_SSCS_SYSTEMUPDATE_PASSWORD
        - name: s2s-micro
          alias: IDAM_S2S_AUTH_MICROSERVICE
        - name: sscs-s2s-secret
          alias: IDAM_S2S_AUTH_TOTP_SECRET
        - name: AppInsightsInstrumentationKey
  environment:
    CORE_CASE_DATA_API_URL: "http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    IDAM_API_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
    IDAM_OAUTH2_REDIRECT_URL: "https://evidence-sharing-preprod.sscs.reform.hmcts.net"
    IDAM_S2S_AUTH: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    RD_LOCATION_REF_API_URL: "http://rd-location-ref-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    MIGRATION_ACCESS_MANAGEMENT_ENABLED: false
    MIGRATION_LOCATION_DATA_ENABLED: false
    MIGRATION_CASE_ID: 1111111111111111
